"""HistoricalAnalogDetailWorkflow — Tier 2 deep dive (PRD Section 4.4).

Full breakdown of each analog period identified by HistoricalAnalogWorkflow:
duration, instrument performance during the period (return, drawdown,
volatility — via the same math BacktestWorkflow uses), and a short list of
likely catalysts for the regime, generated by the LLM and explicitly flagged
as [Agent inference] since catalyst attribution is judgment, not data.

User-initiated only — never run automatically. Consumes HistoricalAnalogWorkflow
(analog periods) and InstrumentAnalysisWorkflow/thesis (instrument, direction)
from WorkflowContext. Fetches its own IBKR price history, same as the other
deep dive workflows.
"""

from __future__ import annotations

import json
import logging

from app.integrations.anthropic_client import AnthropicClient
from app.integrations.ibkr_client import IBKRClient, IBKRClientError
from app.workflows.analysis_utils import (
    bars_to_closes,
    compute_period_stats,
    parse_period_end,
    parse_period_start,
)
from app.workflows.base import (
    BaseWorkflow,
    Citation,
    CitationSourceType,
    WorkflowContext,
    WorkflowResult,
    WorkflowStatus,
)

logger = logging.getLogger(__name__)

_PRICE_PERIOD = "10y"
_BAR_SIZE = "1d"

_SYSTEM_PROMPT = """\
You are a macro research analyst providing historical context for analog \
periods identified in a trade thesis's research.

You will be given a list of historical analog periods, each with a label, \
the macro conditions present, and a summary of what happened during the \
period.

For each period, list 1-3 likely real-world catalysts or events that plausibly \
drove the regime (e.g. a specific Fed decision, a geopolitical event, a data \
surprise). Base this on your knowledge of the historical period, not on the \
data provided.

Respond with a JSON object with exactly two keys:
- "periods": a list of objects, each with:
  - "label": the exact label string from the input
  - "likely_catalysts": list of 1-3 strings, each starting with "[Agent inference]"
- "agent_inferences": list of any additional reasoning not tied to a specific \
period, each starting with "[Agent inference]"

Respond only with the JSON object. No markdown fences, no preamble.\
"""


def _duration_months(start_str: str, end_str: str) -> int:
    """Inclusive month count between 'YYYY-MM' strings, e.g. 2018-10..2019-01 = 4."""
    start_year, start_month = map(int, start_str.split("-"))
    end_year, end_month = map(int, end_str.split("-"))
    return (end_year * 12 + end_month) - (start_year * 12 + start_month) + 1


def _build_user_message(analogs: list[dict]) -> str:
    lines = []
    for analog in analogs:
        lines.append(f"Label: {analog.get('label', '')}")
        lines.append(f"  Macro conditions: {analog.get('macro_conditions', {})}")
        lines.append(f"  Outcome summary: {analog.get('outcome_summary', '')}")
        lines.append("")
    return "\n".join(lines)


class HistoricalAnalogDetailWorkflow(BaseWorkflow):
    """Full breakdown of each historical analog period.

    Outputs (structured_output):
        instrument (str), direction (str)
        periods (list[dict]): one entry per analog period, each with label,
            start_date, end_date, duration_months, macro_conditions,
            similarity_rationale, outcome_summary (all carried over from
            HistoricalAnalogWorkflow), plus total_return, max_drawdown,
            volatility, directionally_correct, n_trading_days (None if
            insufficient price history), and likely_catalysts
            ([Agent inference] list from the LLM).
    """

    name = "HistoricalAnalogDetailWorkflow"
    description = (
        "Deep dive: full breakdown of each historical analog period — "
        "duration, instrument performance (return/drawdown/volatility), and "
        "LLM-identified likely catalysts for the regime."
    )
    required_inputs = ["title", "direction", "time_horizon"]
    model: str = "claude-sonnet-4-6"

    def __init__(
        self,
        ibkr_client: IBKRClient | None = None,
        anthropic_client: AnthropicClient | None = None,
    ) -> None:
        self._ibkr = ibkr_client
        self._anthropic = anthropic_client

    def execute(self, thesis, context: WorkflowContext) -> WorkflowResult:  # noqa: C901
        if self._ibkr is None or self._anthropic is None:
            from app.core.settings import get_settings

            settings = get_settings()
        else:
            settings = None  # type: ignore[assignment]

        anthropic = self._anthropic or AnthropicClient(
            api_key=settings.anthropic_api_key,
            db=context.db,
        )

        if self._ibkr is None:
            if context.pod_settings is None:
                raise ValueError(
                    "HistoricalAnalogDetailWorkflow requires context.pod_settings "
                    "to construct IBKRClient — ensure the caller sets it."
                )
            ibkr = IBKRClient(
                base_url=settings.ibkr_base_url,
                account_id=settings.ibkr_account_id,
                paper_account_id=settings.ibkr_paper_account_id,
                pod_settings=context.pod_settings,
            )
        else:
            ibkr = self._ibkr

        agent_inferences: list[str] = []
        citations: list[Citation] = []

        analog_result = context.get_result("HistoricalAnalogWorkflow")
        instrument_result = context.get_result("InstrumentAnalysisWorkflow")

        analogs: list[dict] = (
            analog_result.structured_output.get("analogs", [])
            if analog_result is not None
            else []
        )
        if analog_result is None:
            agent_inferences.append(
                "[Agent inference] HistoricalAnalogWorkflow result was not "
                "available — historical analog detail could not be produced."
            )

        instruments_info: dict[str, dict] = {}
        if instrument_result is not None:
            instruments_info = instrument_result.structured_output.get(
                "instruments", {}
            )
        if not instruments_info:
            for instr in list(getattr(thesis, "instruments", []) or []):
                direction = (
                    instr.direction.value
                    if hasattr(instr.direction, "value")
                    else str(instr.direction)
                )
                role = (
                    instr.role.value
                    if hasattr(instr.role, "value")
                    else str(instr.role)
                )
                instruments_info[instr.instrument] = {
                    "direction": direction,
                    "role": role,
                }

        primary_symbol: str | None = None
        primary_direction = "long"
        for symbol, info in instruments_info.items():
            if info.get("role", "primary") == "primary":
                primary_symbol = symbol
                primary_direction = info.get("direction", "long")
                break
        if primary_symbol is None and instruments_info:
            primary_symbol, _info = next(iter(instruments_info.items()))
            primary_direction = _info.get("direction", "long")

        if not analogs:
            return WorkflowResult(
                workflow_name=self.name,
                status=WorkflowStatus.PARTIAL,
                structured_output={
                    "instrument": primary_symbol,
                    "direction": primary_direction,
                    "periods": [],
                },
                citations=citations,
                agent_inferences=agent_inferences,
                raw_output="",
            )

        closes = None
        if primary_symbol is not None:
            try:
                price_history = ibkr.get_price_history(
                    symbol=primary_symbol, period=_PRICE_PERIOD, bar_size=_BAR_SIZE
                )
                citations.append(
                    Citation(
                        source_type=CitationSourceType.IBKR,
                        label=(
                            f"IBKR:{primary_symbol} price_history, "
                            f"{price_history.retrieved_at.isoformat()}"
                        ),
                        url=None,
                        retrieval_date=price_history.retrieved_at.date(),
                    )
                )
                closes = bars_to_closes(price_history.bars)
            except IBKRClientError as exc:
                logger.warning(
                    "HistoricalAnalogDetailWorkflow: failed to fetch price "
                    "history for %s: %s",
                    primary_symbol,
                    exc,
                )
                agent_inferences.append(
                    f"[Agent inference] Price history for {primary_symbol} could "
                    "not be retrieved from IBKR — performance stats are unavailable."
                )
        else:
            agent_inferences.append(
                "[Agent inference] No instrument data was available — "
                "performance stats are unavailable for these periods."
            )

        # --- Build per-period quantitative detail ---
        periods_detail: list[dict] = []
        for analog in analogs:
            start_str = analog.get("start_date", "")
            end_str = analog.get("end_date", "")
            label = analog.get("label", "")

            detail: dict = {
                "label": label,
                "start_date": start_str,
                "end_date": end_str,
                "macro_conditions": analog.get("macro_conditions", {}),
                "similarity_rationale": analog.get("similarity_rationale", ""),
                "outcome_summary": analog.get("outcome_summary", ""),
                "total_return": None,
                "max_drawdown": None,
                "volatility": None,
                "directionally_correct": None,
                "n_trading_days": None,
                "likely_catalysts": [],
            }

            try:
                detail["duration_months"] = _duration_months(start_str, end_str)
            except (ValueError, AttributeError):
                detail["duration_months"] = None

            if closes is not None and start_str and end_str:
                try:
                    stats = compute_period_stats(
                        closes,
                        parse_period_start(start_str),
                        parse_period_end(end_str),
                        primary_direction,
                    )
                except (ValueError, AttributeError):
                    stats = None
                if stats is not None:
                    detail.update(
                        {
                            "total_return": stats["total_return"],
                            "max_drawdown": stats["max_drawdown"],
                            "volatility": stats["volatility"],
                            "directionally_correct": stats["directionally_correct"],
                            "n_trading_days": stats["n_trading_days"],
                        }
                    )
                else:
                    agent_inferences.append(
                        f"[Agent inference] Insufficient price data for period "
                        f"'{label}' ({start_str} – {end_str}) — performance "
                        "stats unavailable."
                    )

            periods_detail.append(detail)

        # --- LLM catalyst identification ---
        user_message = _build_user_message(analogs)
        response = anthropic.complete(
            messages=[{"role": "user", "content": user_message}],
            model=self.model,
            task_type="historical_analog_detail",
            workflow_run_id=context.current_workflow_run_id,
            thesis_id=thesis.id,
            pod_id=getattr(thesis, "pod_id", None),
            max_tokens=1024,
            system=_SYSTEM_PROMPT,
        )

        try:
            parsed = json.loads(response.content)
            llm_periods = parsed.get("periods", [])
            llm_inferences = parsed.get("agent_inferences", [])
        except (json.JSONDecodeError, AttributeError):
            logger.warning(
                "HistoricalAnalogDetailWorkflow: LLM response was not valid JSON"
            )
            llm_periods = []
            llm_inferences = []

        catalysts_by_label = {
            p.get("label"): p.get("likely_catalysts", []) for p in llm_periods
        }
        for detail in periods_detail:
            detail["likely_catalysts"] = catalysts_by_label.get(detail["label"], [])

        agent_inferences.extend(llm_inferences)

        return WorkflowResult(
            workflow_name=self.name,
            status=WorkflowStatus.COMPLETED,
            structured_output={
                "instrument": primary_symbol,
                "direction": primary_direction,
                "periods": periods_detail,
            },
            citations=citations,
            agent_inferences=agent_inferences,
            raw_output=response.content,
        )
